<?php

// Canonical reference data for incident reports.
//
// These lists are the server-side authority for validating submitted incidents.
// The browser copies live in public/js/data.js, which drives the autocomplete
// UI; if you add a location or type, update both files (and add coordinates in
// public/js/map.js for any new location, or it will not appear on the map).

return [

    'locations' => [
        'Achrafieh',
        'Adloun',
        'Adma',
        'Aichiye',
        'Ain Aar',
        'Ain Dara',
        'Ain Ebel',
        'Ain Saadeh',
        'Ain Zhalta',
        'Aintoura',
        'Aita al-Shaab',
        'Ajaltoun',
        'Akkar',
        'Akoura',
        'Aley',
        'Amchit',
        'Amioun',
        'Anfeh',
        'Anjar',
        'Antelias',
        'Aramoun',
        'Araya',
        'Arsal',
        'Baabda',
        'Baakline',
        'Baalbek',
        'Baaqline',
        'Baissour',
        'Ballouneh',
        'Baouchrieh',
        'Bar Elias',
        'Barsa',
        'Batroun',
        'Bchamoun',
        'Bcharre',
        'Beddawi',
        'Beit Chabab',
        'Beit Mery',
        'Beiteddine',
        'Beirut',
        'Bent Jbeil',
        'Bhamdoun',
        'Bikfaya',
        'Bint Jbeil',
        'Bisri',
        'Bkassine',
        'Blat',
        'Borj Hammoud',
        'Boushriyeh',
        'Bqaatouta',
        'Broummana',
        'Bsharri',
        'Btater',
        'Byblos',
        'Chebaa',
        'Chekka',
        'Choueifat',
        'Chouf',
        'Chtaura',
        'Dahiyeh',
        'Damour',
        'Dbayeh',
        'Deir el Ahmar',
        'Deir el Qamar',
        'Deir Mimas',
        'Dekwaneh',
        'Dhour el Choueir',
        'Dohat Aramoun',
        'Douma',
        'Ehden',
        'Enfeh',
        'Falougha',
        'Faraya',
        'Fanar',
        'Ferzol',
        'Fnaidek',
        'Gemmayzeh',
        'Ghazir',
        'Ghobeiry',
        'Hadat',
        'Halba',
        'Hammana',
        'Haret Hreik',
        'Harissa',
        'Hasbaya',
        'Hazmieh',
        'Hermel',
        'Hrajel',
        'Insariyeh',
        'Iaat',
        'Jal el Dib',
        'Jbaa',
        'Jbeil',
        'Jdeideh',
        'Jezzine',
        'Jiyeh',
        'Jounieh',
        'Joub Jannine',
        'Kafarshima',
        'Kahale',
        'Kab Elias',
        'Kaslik',
        'Keserwan',
        'Ketermaya',
        'Kfar Debiane',
        'Kfar Hbab',
        'Kfar Kila',
        'Kfar Mashki',
        'Kfar Matta',
        'Kfar Nabrakh',
        'Kfar Remen',
        'Kfar Tibnit',
        'Kfardebian',
        'Khalde',
        'Khiam',
        'Koura',
        'Labweh',
        'Laqlouq',
        'Maameltein',
        'Machghara',
        'Maghdouche',
        'Majdal Anjar',
        'Mansourieh',
        'Mar Mikhael',
        'Marjayoun',
        'Mays al-Jabal',
        'Metn',
        'Mina',
        'Minieh',
        'Monsef',
        'Mukhtara',
        'Msaylha',
        'Nabatieh',
        'Naameh',
        'Nabi Sheet',
        'Naccache',
        'Naqoura',
        'Niha',
        'Ouadi Chahrour',
        'Oyoun el Siman',
        'Qana',
        'Qartaba',
        'Qbaiyat',
        'Qobayat',
        'Rabweh',
        'Rachaiya',
        'Ras Baalbek',
        'Ras Beirut',
        'Rashaya',
        'Rayak',
        'Rechmaya',
        'Rmeich',
        'Roumieh',
        'Saghbine',
        'Saida',
        'Saifi',
        'Saoufar',
        'Sarafand',
        'Sarba',
        'Sawfar',
        'Sidon',
        'Sin el Fil',
        'Sir Dinnieh',
        'Sohmor',
        'Sofar',
        'Souk el Gharb',
        'Tabarja',
        'Taanayel',
        'Taalabaya',
        'Taibe',
        'Tebnine',
        'Temnine al-Fawqa',
        'Tripoli',
        'Tyre',
        'Verdun',
        'Zahlé',
        'Zgharta',
        'Zouk Mikael',
        'Zouk Mosbeh',
        'Zrariye',
    ],

    'types' => [
        'Airstrike',
        'Ambush',
        'Armed Clash',
        'Artillery Fire',
        'Assassination Attempt',
        'Blockade',
        'Bombing',
        'Car Bomb',
        'Chemical Attack',
        'Cluster Munitions',
        'Cyber Attack',
        'Demolition',
        'Drone Strike',
        'Evacuation',
        'Explosion',
        'Fire',
        'Gunfire',
        'Hostage Situation',
        'IED (Improvised Explosive Device)',
        'Incursion',
        'Infantry Advance',
        'Kidnapping',
        'Land Mine',
        'Looting',
        'Missile Launch',
        'Mortar Fire',
        'Naval Bombardment',
        'Power Outage',
        'Raid',
        'Rocket Attack',
        'Roadblock',
        'Shelling',
        'Sniper Fire',
        'Sonic Boom',
        'Supply Drop',
        'Surveillance Drone',
        'Tear Gas',
        'Tunnel Discovery',
        'White Phosphorus',
        'Other',
    ],

    // How far back a reported incident time may be, and how long after creation
    // the author may still edit their own report.
    'max_report_age_hours' => 24,
    'edit_window_minutes' => 30,

];
